iemacies/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("main.urls")),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.subjectList, name="home"),

    path('login/', views.userLogin, name="login"),
    path('register/', views.userRegister, name="register"),
    path('logout/', views.userLogout, name="logout"),

    path("profile/<int:pk>", views.profileDetail, name="profile_detail"),
    path("profile/<int:pk>/update", views.profileUpdate, name="profile_update"),

    path("chat/", views.chatList, name="chat_list"),
    path("chat/<int:pk>", views.chatDetail, name="chat_detail"),

    path("advert/", views.advertList, name="advert_list"),
    path("advert/create", views.advertCreate, name="advert_create"),
    path("advert/create/<int:pk>",
         views.advertCreate, name="advert_create"),
    path("advert/<int:pk>", views.advertDetail, name="advert_detail"),
    path("advert/<int:pk>/update",
         views.advertUpdate, name="advert_update"),

    path("application/create/<int:pk>",
         views.createApplication, name="application_create"),
    path("application/<int:pk>", views.viewApplication, name="application_detail"),
    path("application/<int:pk>/update",
         views.updateApplication, name="application_update"),

    path("review/create/<int:pk>", views.createReview, name="review_create"),
    path("review/<int:pk>", views.viewReview, name="review_detail"),
    path("review/<int:pk>/update", views.updateReview, name="review_update"),

    path("subject/", views.subjectList, name="subject_list"),
    path("subject/<int:pk>", views.subjectDetail, name="subject_detail"),

    path("map/", views.map, name="map"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator


class Profile(models.Model):
    full_name = models.CharField(max_length=100, blank=True)
    description = models.TextField(blank=True)

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def reachable_users(self) -> models.QuerySet[User]:
        """
        Returns a queryset of users who are reachable by the current user.

        The reachable users include both the teachers who have ongoing applications
        from the current user and the students who have ongoing applications to the
        advertisements owned by the current user.

        Returns:
            A queryset of User objects representing the reachable users.
        """
        teachers = set(Application.objects.filter(
            applicant=self.user, status='ONGOING').values_list('advert__owner', flat=True))
        students = set(Application.objects.filter(
            advert__owner=self.user, status='ONGOING').values_list('applicant', flat=True))
        return User.objects.filter(id__in=teachers | students | {self.user.id})

    def viewable_users(self) -> models.QuerySet[User]:
        """
        Returns a queryset of users that can be viewed by the current user.

        This method retrieves the set of reachable users and existing chats
        involving the current user. It then filters the User queryset based on
        the union of these sets.

        Returns:
            A queryset of User objects that can be viewed by the current user.
        """
        application_relations = set(
            self.reachable_users().values_list('id', flat=True))
        existing_chats = set(Chat.objects.filter(sender=self.user).values_list('receiver', flat=True)) | set(
            Chat.objects.filter(receiver=self.user).values_list('sender', flat=True))
        return User.objects.filter(id__in=application_relations | existing_chats)

    def __str__(self) -> str:
        return self.user.username


class Chat(models.Model):
    message = models.CharField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    sender = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='sender'
    )
    receiver = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='receiver'
    )

    def __str__(self) -> str:
        return f'{self.sender} -> {self.receiver}'


class Advert(models.Model):
    description = models.TextField(blank=True)
    price = models.IntegerField()
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='adverts'
    )
    subject = models.ForeignKey(
        'Subject',
        on_delete=models.CASCADE,
        related_name='adverts'
    )

    def get_average_rating(self) -> float:
        """
        Calculates and returns the average rating of the reviews for this object.

        Returns:
            float: The average rating.
        """
        return self.reviews.aggregate(models.Avg('rating'))['rating__avg']

    def __str__(self) -> str:
        return f'{self.owner} - {self.subject}'

    class Meta:
        unique_together = [['owner', 'subject']]


class Application(models.Model):
    class Status(models.TextChoices):
        PENDING = 'PENDING'
        ONGOING = 'ONGOING'
        FINISHED = 'FINISHED'
        REJECTED = 'REJECTED'

    description = models.CharField(max_length=1000)
    status = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.PENDING
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    advert = models.ForeignKey(
        Advert,
        on_delete=models.CASCADE,
        related_name='applications'
    )
    applicant = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='applications'
    )

    class Meta:
        unique_together = [['advert', 'applicant']]

    def __str__(self) -> str:
        return f'{self.applicant} - {self.advert}'


class Review(models.Model):
    review = models.CharField(max_length=1000, blank=True)
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(10)]
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    advert = models.ForeignKey(
        Advert,
        on_delete=models.CASCADE,
        related_name='reviews'
    )
    reviewer = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='reviews'
    )

    class Meta:
        unique_together = [['advert', 'reviewer']]

    def __str__(self) -> str:
        return f'{self.reviewer} - {self.advert}'


class Subject(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    sub_subjects = models.ManyToManyField(
        'Subject',
        blank=True,
        related_name='sup_subjects'
    )

    def __str__(self):
        return self.title

class Map(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

main/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from main.forms import UserForm, ProfileForm, AdvertForm, ApplicationForm, ReviewForm, SubjectSearchForm
from main.models import Profile, Chat, Advert, Application, Review, Subject


# ---------------------------- Authentication Views ---------------------------


def userLogin(request: HttpRequest) -> HttpResponse:
    """
    Handles the user login functionality.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The HTTP response object.
    """
    template_name = 'main/user_login.html'

    if request.user.is_authenticated:
        return redirect('home')

    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)

        if form.is_valid():
            user = authenticate(
                request,
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password']
            )

            login(request, user)

            messages.success(request, 'Logged in as ' + user.username)

            return redirect('home')
        else:
            messages.error(request, form.error_messages)

    return render(request, template_name, {'form': form})


def userRegister(request: HttpRequest) -> HttpResponse:
    """
    View function for user registration.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The HTTP response object.
    """
    template_name = 'main/user_register.html'

    if request.user.is_authenticated:
        return redirect('home')

    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            user.profile = Profile.objects.create(user=user)

            login(request, user)

            messages.success(request, 'User account was created')

            return redirect('home')
        else:
            messages.error(request, form.error_messages)

    return render(request, template_name, {'form': form})


def userLogout(request: HttpRequest) -> HttpResponse:
    """
    Logs out the user and redirects to the home page.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponseRedirect: A redirect response to the home page.
    """
    logout(request)

    messages.success(request, 'Logged out successfully')

    return redirect('home')


# ------------------------------ Profile Views --------------------------------


def profileDetail(request: HttpRequest, pk: int) -> HttpResponse:
    """
    View function to display the details of a profile.

    Args:
        request (HttpRequest): The HTTP request object.
        pk (int): The primary key of the profile.

    Returns:
        HttpResponse: The HTTP response containing the rendered template.
    """
    template_name = 'main/profile_detail.html'

    profile = get_object_or_404(User, pk=pk).profile

    return render(request, template_name, {'profile': profile})


@login_required(login_url='login')
def profileUpdate(request: HttpRequest, pk: int) -> HttpResponse:
    """
    View function for updating a user profile.

    Args:
        request (HttpRequest): The HTTP request object.
        pk (int): The primary key of the profile to be updated.

    Returns:
        HttpResponse: The HTTP response object.
    """
    template_name = 'main/profile_form.html'

    profile = get_object_or_404(Profile, pk=pk)

    if request.user != User.objects.get(id=pk):
        messages.error(request, 'You don\'t have edit access to this profile!')
        return redirect(reverse('profile_detail', args=[pk]))

    user_form = UserForm(instance=profile.user)
    profile_form = ProfileForm(instance=profile)

    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=profile.user)
        profile_form = ProfileForm(request.POST, instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

            messages.success(request, 'Profile was updated successfully!')

            return redirect(reverse('profile_detail', args=[pk]))
        else:
            messages.error(request, user_form.errors.as_text())
            messages.error(request, profile_form.errors.as_text())

    return render(request, template_name, {'user_form': user_form, 'profile_form': profile_form})


# ------------------------------ Chat Views -----------------------------------


@login_required(login_url='login')
def chatList(request: HttpRequest) -> HttpResponse:
    """
    View function that displays the list of chats for the logged-in user.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The rendered chat list template with the chats context.
    """
    template_name = 'main/chat_list.html'

    chats = request.user.profile.viewable_users()

    return render(request, template_name, {'chats': chats})


@login_required(login_url='login')
def chatDetail(request: HttpRequest, pk: int) -> HttpResponse:
    """
    View function for displaying the chat detail page. View allows viewing all the
    messages that have been sent, but only allows sending to users that currently
    have an active application with sender.

    Args:
        request (HttpRequest): The HTTP request object.
        pk (int): The primary key of the user to chat with.

    Returns:
        HttpResponse: The HTTP response object.
    """
    template_name = 'main/chat_detail.html'

    if not User.objects.filter(id=pk).exists():
        messages.error(request, 'This user does not exist!')
        return redirect('home')

    if not request.user.profile.viewable_users().filter(id=pk).exists():
        messages.error(request, 'You don\'t have access to this chat!')
        return redirect('home')

    chat = Chat.objects.filter(sender=request.user, receiver=pk) | Chat.objects.filter(
        sender=pk, receiver=request.user).order_by('created_at')
    receiver = User.objects.get(id=pk)

    if request.method == 'POST':
        if not request.user.profile.reachable_users().filter(id=pk).exists():
            messages.error(
                request, 'You can no longer send messages to this user!')
            return redirect(reverse('chat_detail', args=[pk]))

        message = request.POST.get('message')
        if message:
            chat = Chat.objects.create(
                sender=request.user, receiver=User.objects.get(id=pk), message=message)
            return redirect(reverse('chat_detail', args=[pk]))
        else:
            messages.warning(request, 'Message cannot be empty!')

    return render(request, template_name, {'chat': chat, 'receiver': receiver})


# ------------------------------ Advert Views ---------------------------------


def advertList(request: HttpRequest) -> HttpResponse:
    """
    View function that renders a list of active adverts.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The HTTP response object containing the rendered template.
    """
    template_name = 'main/advert_list.html'

    adverts = Advert.objects.filter(is_active=True)

    return render(request, template_name, {'advert_list': adverts})


@login_required(login_url='login')
def advertCreate(request: HttpRequest, pk: int = None) -> HttpResponse:
    """
    View function for creating an advert. If the pk argument is provided, the
    subject field of the form will be pre-filled with the subject with the given
    primary key. If the user has already created an advert for the subject, they
    will be redirected to the update view.

    Args:
        request (HttpRequest): The HTTP request object.
        pk (int, optional): The primary key of the subject. Defaults to None.

    Returns:
        HttpResponse: The HTTP response object.
    """
    template_name = 'main/advert_form.html'

    initial_data = {}
    if pk:
        initial_data['subject'] = pk

    if Advert.objects.filter(subject=pk, owner=request.user).exists():
        messages.warning(
            request, 'You have already created an advert for this subject!')
        return redirect(reverse('advert_update', args=[Advert.objects.get(subject=pk, owner=request.user).id]))

    if request.method == 'POST':
        form = AdvertForm(request.POST)
        if form.is_valid():
            advert = form.save(commit=False)

            if Advert.objects.filter(subject=advert.subject, owner=request.user).exists():
                messages.warning(
                    request, 'You have already created an advert for this subject!')
                return redirect(reverse('advert_update', args=[Advert.objects.get(subject=advert.subject, owner=request.user).id]))

            advert.owner = request.user
            advert.save()
            return redirect('home')
        else:
            messages.error(request, form.errors.as_text())
    else:
        form = AdvertForm(initial=initial_data)

    return render(request, template_name, {'form': form, 'page': 'create'})


def advertDetail(request: HttpRequest, pk: int) -> HttpResponse:
    """
    View function to display the details of an advert.

    Args:
        request (HttpRequest): The HTTP request object.
        pk (int): The primary key of the advert.

    Returns:

main/templates/main/advert_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mx-auto">
    <div class="flex justify-between">
        <h1 class="text-2xl font-bold">{{ advert.owner }}'s <em>{{advert.subject}}</em> advert</h1>

        {% if user.is_authenticated %}
        <span>
            {% if user == advert.owner %}
            <a href="{% url 'advert_update' advert.id %}" class="inline-block bg-green-500 text-white py-2 px-4 rounded hover:bg-blue-600">Update advert</a>
            {% elif user.profile.user.groups.all.0.name != 'teacher' %}
            <a href="{% url 'application_create' advert.id %}"
                class="inline-block bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600">Create application</a>
            <a href="{% url 'review_create' advert.id %}"
                class="inline-block bg-yellow-500 text-white py-2 px-4 rounded hover:bg-blue-600">Create review</a>
            {% endif %}
        </span>
        {% endif %}
    </div>

    <h2 class="text-xl font-bold mt-4">Average Rating</h2>
    <p>{{ advert.get_average_rating|default:"No reviews"}}</p>

    <h2 class="text-xl font-bold mt-4">Description</h2>
    <p>{{ advert.description }}</p>

    <h2 class="text-xl font-bold mt-4">Reviews</h2>
    <table class="border-collapse w-full mt-4">
        <thead>
            <tr>
                <th class="border border-blue-500 px-4 py-2">Reviewer</th>
                <th class="border border-blue-500 px-4 py-2">Rating</th>
                <th class="border border-blue-500 px-4 py-2">Review</th>
                <th class="border border-blue-500 px-4 py-2">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for review in advert.reviews.all %}
            <tr>
                <td class="border border-blue-500 px-4 py-2">
                    <a href="{% url 'profile_detail' review.reviewer.id %}" class="text-blue-500">
                        {{ review.reviewer }}</a>
                </td>
                <td class="border border-blue-500 px-4 py-2">{{ review.rating }}</td>
                <td class="border border-blue-500 px-4 py-2">{{ review.review }}</td>
                <td class="border border-blue-500 px-4 py-2">
                    <a href="{% url 'review_detail' review.id %}" class="text-blue-500">View</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if request.user.is_authenticated and request.user == advert.owner %}
    <h2 class="text-xl font-bold mt-4">Applications</h2>
    <table class="border-collapse w-full mt-4">
        <thead>
            <tr>
                <th class="border border-blue-500 px-4 py-2">Applicant</th>
                <th class="border border-blue-500 px-4 py-2">Status</th>
                <th class="border border-blue-500 px-4 py-2">Description</th>
                <th class="border border-blue-500 px-4 py-2">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for application in advert.applications.all %}
            <tr>
                <td class="border border-blue-500 px-4 py-2">
                    <a href="{% url 'profile_detail' application.applicant.id %}" class="text-blue-500">
                        {{ application.applicant }}</a>
                </td>
                <td class="border border-blue-500 px-4 py-2">{{ application.status }}</td>
                <td class="border border-blue-500 px-4 py-2">{{ application.description }}</td>
                <td class="border border-blue-500 px-4 py-2">
                    <a href="{% url 'application_detail' application.id %}" class="text-blue-500">View</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}

</div>

{% endblock %}

main/templates/main/advert_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container mx-auto p-4">

    <h1 class="text-2xl font-bold mb-4">{{ page|capfirst }} Advert</h1>

    <form action="" method="post" class="max-w-lg mx-auto">
        {% csrf_token %}

        <div class="mb-4">
            <label for="subject" class="block text-gray-700 text-sm font-bold mb-2">Subject</label>
            <select name="subject" id="subject"
                class="w-full px-3 py-2 border rounded focus:outline-none focus:border-blue-500">
                <option value="">---------</option>
                {% for option in form.fields.subject.queryset %}
                <option value="{{ option.id }}" {% if form.subject.value|add:'0' == option.id|add:'0' %}selected{%endif%}>
                    {{ option.title }}
                </option>
                {% endfor %}
            </select>
            <div class="text-red-500 text-sm">{{form.subject.errors}}</div>
        </div>

        <div class="mb-4">
            <label for="id_description" class="block text-gray-700 text-sm font-bold mb-2">Description</label>
            <textarea id="id_description" name="description"
                class="w-full px-3 py-2 border rounded focus:outline-none focus:border-blue-500">{{form.description.value|default:''}}</textarea>
                <div class="text-red-500 text-sm">{{ form.description.errors }}</div>
        </div>

        <div class="mb-4">
            <label for="id_price" class="block text-gray-700 text-sm font-bold mb-2">Price</label>
            <input id="id_price" type="text" name="price"
                class="w-full px-3 py-2 border rounded focus:outline-none focus:border-blue-500"
                value="{{form.price.value|default:''}}">
                <div class="text-red-500 text-sm">{{ form.price.errors }}</div>
        </div>

        <div class="mb-4">
            <label for="id_active" class="text-gray-700 text-sm font-bold mb-2">Is active</label>
            <input id="id_active" type="checkbox" name="is_active"
                class="border rounded focus:outline-none focus:border-blue-500" {% if form.is_active %}checked{%endif%}>
                <div class="text-red-500 text-sm">{{ form.active.errors }}</div>
        </div>

        <button type="submit" class="bg-blue-500 text-white font-bold py-2 px-4 rounded">
            Submit
        </button>
    </form>

</div>

{% endblock %}

main/templates/main/application_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mx-auto p-4">

    <div class="flex justify-between">
        <h1 class="text-3xl font-bold mb-4">{{ application.applicant }} - {{ application.advert.subject.title }}</h1>
        {% if user.is_authenticated and user == application.applicant %}
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            <a href="{% url 'application_update' application.id %}" class="text-white">Update application</a>
        </button>
        {% endif %}
    </div>

    <div class="mb-8">
        <h2 class="text-xl font-bold mb-2">Description</h2>
        <p>{{ application.description }}</p>
    </div>

    <div class="mb-8">
        <h2 class="text-xl font-bold mb-2">Status</h2>
        <p class="text-yellow-300 font-bold">{{ application.status }}</p>
    </div>

    {% if user == application.advert.owner %}
    <form method="post" class="mb-8">
        {% csrf_token %}
        {% if application.status.lower == 'pending' %}
        <button type="submit" name="status" value="ongoing"
            class="bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-blue-600 focus:outline-none focus:border-blue-700">
            Accept
        </button>
        <button type="submit" name="status" value="rejected"
            class="bg-red-500 text-white py-2 px-4 rounded-md hover:bg-red-600 focus:outline-none focus:border-red-700 ml-2">
            Reject
        </button>
        {% elif application.status.lower == 'finished' or application.status.lower == 'rejected'%}
        <button type="submit" name="status" value="ongoing"
            class="bg-green-500 text-white py-2 px-4 rounded-md hover:bg-green-600 focus:outline-none focus:border-green-700">
            Reopen
        </button>
        {% endif %}
    </form>
    {% endif %}

    {% if application.status.lower == 'ongoing' %}
    <form method="post">
        {% csrf_token %}
        <button type="submit" name="status" value="finished"
            class="bg-red-500 text-white py-2 px-4 rounded-md hover:bg-red-600 focus:outline-none focus:border-red-700">
            End
        </button>
    </form>
    {% endif %}

</div>

{% endblock %}

main/templates/main/application_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container mx-auto p-10">

    <h1 class="text-3xl font-bold mb-4">{{page|capfirst}} Application for <em>
            {{ advert_name }}</em></h1>

    <form method="post" class="max-w-md mx-auto ">
        {% csrf_token %}

        <div class="mb-4">
            <label for="description" class="block text-gray-700 text-sm font-bold mb-2">Description:</label>
            <textarea name="description" id="description"
                class="w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500" cols="30"
                rows="10">{{ form.description.value|default:'' }}</textarea>
            <div class="text-red-500 text-sm">{{form.description.errors}}</div>
        </div>

        <button type="submit"
            class="w-full bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-blue-600 focus:outline-none focus:border-blue-700">
            {{page|capfirst}}
        </button>
    </form>

</div>

{% endblock %}

main/templates/main/chat_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mx-auto p-4">
    <h1 class="text-3xl font-bold mb-4">
        Chat with 
        <a href="{% url 'profile_detail' receiver.id %}" class="text-blue-500 hover:underline">
            {{ receiver.username }}
        </a>
    </h1>
    

    <div class="bg-gray-100 p-4 rounded-lg mb-4">
        <ul class="divide-y divide-gray-200">
            {% for message in chat %}
            <li class="py-2 {% if message.sender.username == user.username %} text-right {% endif %}">
                <span class="text-gray-500">{{ message.sender.username }}
                    ({{ message.created_at|date:"F d, Y H:i"}}):</span>
                <p class="mt-1">{{ message.message }}</p>
            </li>
            {% endfor %}
        </ul>
    </div>

    <form method="post" class="flex items-center space-x-4">
        {% csrf_token %}
        <input type="text" name="message"
            class="flex-grow p-2 border rounded-md focus:outline-none focus:border-blue-500">
        <button type="submit"
            class="bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-blue-600 focus:outline-none focus:border-blue-700">
            Send
        </button>
    </form>
</div>

{% endblock %}

main/templates/main/chat_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container mx-auto">
    <table class="min-w-full bg-white border border-blue-500 mt-4">
        <thead>
            <tr>
                <th class="border py-2 px-4">Username</th>
                <th class="border py-2 px-4">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for user in chats %}
            <tr class="hover:bg-gray-100">
                <td class="border py-2 px-4">
                    <a href="{% url 'profile_detail' user.id %}" class="text-blue-500 hover:underline">
                        {{ user.username }}</a>
                </td>
                <td class="border py-2 px-4">
                    <a href="{% url 'chat_detail' user.id %}" class="text-blue-500 hover:underline">
                        View</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>



{% endblock %}

main/templates/main/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iemācies</title>
</head>

<body>

    {% include 'main/navbar.html' %}

    <hr>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    <hr>
    {% endif %}

    {% block content %}

    {% endblock %}

</body>

</html>

main/templates/main/review_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mx-auto">
    <h1 class="text-3xl font-bold mb-2">{{ review.reviewer }}'s Review of {{ review.advert.owner }}'s
        {{ review.advert.subject.name }} Advert</h1>

    <p class="text-lg text-gray-600">Rating: {{ review.rating }}</p>

    <h2 class="text-xl font-bold mt-4">Review</h2>
    <p class="mt-2 text-gray-800">{{ review.review }}</p>

    <p class="mt-4 text-sm text-gray-500">Created: {{ review.created_at }}</p>

    {% if user.is_authenticated and user == review.reviewer %}
    <a href="{% url 'review_update' review.id %}"
        class="mt-4 inline-block px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition duration-300">Edit</a>
    {% endif %}
</div>

{% endblock %}